title: 淡水鱼的蔚蓝之海
subtitle: 如果大海能够唤回曾经滴爱，我会
description: 如果大海能够唤回曾经滴爱，我会
keywords: ChrisDing, SYuan03, 技术博客, 学习记录
author: SYuan03
language: zh-CN
timezone: Asia/Shanghai

url: https://bblog.031105.xyz
root: /
permalink: posts/:category/:title.html
permalink_defaults: {}
pretty_urls:
  trailing_index: false
  trailing_html: true

source_dir: content
public_dir: dist
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: []

new_post_name: :title.md
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: []
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ""
  wrap: true
  hljs: false

index_generator:
  path: ""
  per_page: 10
  order_by: -date
archive_generator:
  per_page: 10
  yearly: true
  monthly: true
category_generator:
  per_page: 10
tag_generator:
  per_page: 10

feed:
  type: atom
  path: atom.xml
  limit: 0
  content: true
  order_by: -date
search:
  path: search.xml
  field: post
  content: true
  format: html

theme: tide

deploy:
  type: ""
